"""Centralized UI microcopy for the Remote Desktop Manager."""

UI_COPY = {
    "app_title": "Remote Desktop Manager",
    "empty_title": "No Endpoint Selected",
    "empty_subtitle": "Select a device to begin a live session.",
    "connected": "Endpoints",
    "waiting": "Listening for connections…",
    "clients": "Nodes",
    "fps": "FPS",
    "latency": "Latency",
    "rx": "RX",
    "tx": "TX",
    "messages": "Messages",
    "actions": "Actions",
    "activity": "Activity",
    "chat_placeholder": "Type a message…",
    "send": "Send",
    "cancel_task": "Cancel",
    "retry_task": "Retry",
    "lock": "Lock Endpoint",
    "shutdown": "Shutdown",
    "restart": "Restart",
    "file_transfer": "Transfer Queue",
    "file_drop": "Drop files on the viewer to transfer",
    "network_scanner": "Scanner",
    "scan": "Scan",
    "stop": "Stop",
    "active_only": "Active Only",
    "filter_port": "Filter by port",
    "scanner_note": "LAN only — ports 22, 80, 443, 3389",
    "export_csv": "CSV",
    "export_json": "JSON",
    "compare_runs": "Compare",
    "latest_run": "Latest Run",
    "ready_scan": "Ready",
    "stopping_scan": "Stopping…",
    "audit_log": "Event Log",
    "tab_chat": "Chat",
    "tab_controls": "Controls",
    "tab_transfer": "Transfer",
    "tab_scanner": "Scanner",
    "tab_audit": "Logs",
    "no_client_selected": "No Client Selected",
    "no_client_selected_msg": "Select a device before sending files.",
    "invalid_subnet": "Invalid Subnet",
    "no_data": "No Data",
    "no_visible_rows": "No visible rows to export.",
    "export_failed": "Export Failed",
    "history": "History",
    "history_select": "Select a previous run to compare.",
    "scan_comparison": "Scan Comparison",
}
